name: lumen

services:

  0dev:
    build: 
      context: ./
      dockerfile: ./0dev/Dockerfile
    image: marcosbento/lumen:0dev
    profiles:
      - development

  alpine-3.23:
    build: 
      context: ./
      dockerfile: ./alpine-3.23/Dockerfile
    image: marcosbento/lumen:alpine-3.23
    profiles:
      - development

  arch-20260315:
    build: 
      context: ./
      dockerfile: ./arch-20260315/Dockerfile
    image: marcosbento/lumen:arch-20260315
    profiles:
      - development

  debian-11.11:
    build: 
      context: ./
      dockerfile: ./debian-11.11/Dockerfile
    image: marcosbento/lumen:debian-11.11
    profiles:
      - development

  debian-12.13:
    build: 
      context: ./
      dockerfile: ./debian-12.13/Dockerfile
    image: marcosbento/lumen:debian-12.13
    profiles:
      - development

  debian-13.4:
    build: 
      context: ./
      dockerfile: ./debian-13.4/Dockerfile
    image: marcosbento/lumen:debian-13.4
    profiles:
      - development

  fedora-43:
    build: 
      context: ./
      dockerfile: ./fedora-43/Dockerfile
    image: marcosbento/lumen:fedora-43
    profiles:
      - development

  almalinux-8.10:
    build: 
      context: ./
      dockerfile: ./almalinux-8.10/Dockerfile
    image: marcosbento/lumen:almalinux-8.10
    profiles:
      - development
  
  almalinux-9.7:
    build: 
      context: ./
      dockerfile: ./almalinux-9.7/Dockerfile
    image: marcosbento/lumen:almalinux-9.7
    profiles:
      - development
  
  almalinux-10.1:
    build: 
      context: ./
      dockerfile: ./almalinux-10.1/Dockerfile
    image: marcosbento/lumen:almalinux-10.1
    profiles:
      - development

  ubuntu-22.04:
    build: 
      context: ./
      dockerfile: ./ubuntu-22.04/Dockerfile
    image: marcosbento/lumen:ubuntu-22.04
    profiles:
      - development

  ubuntu-24.04:
    build: 
      context: ./
      dockerfile: ./ubuntu-24.04/Dockerfile
    image: marcosbento/lumen:ubuntu-24.04
    profiles:
      - development
      
  opensuse-tumbleweed:
    build: 
      context: ./
      dockerfile: ./opensuse-tumbleweed/Dockerfile
    image: marcosbento/lumen:opensuse-tumbleweed
    profiles:
      - development
