name: lumen

services:

  0dev:
    build: 
      context: ./
      dockerfile: ./0dev/Dockerfile
    image: marcosbento/lumen:0dev
    profiles:
      - development

  arch-20250622:
    build: 
      context: ./
      dockerfile: ./arch-20250622/Dockerfile
    image: marcosbento/lumen:arch-20250622
    profiles:
      - development

  debian-11.11:
    build: 
      context: ./
      dockerfile: ./debian-11.11/Dockerfile
    image: marcosbento/lumen:debian-11.11
    profiles:
      - development

  debian-12.12:
    build: 
      context: ./
      dockerfile: ./debian-12.12/Dockerfile
    image: marcosbento/lumen:debian-12.12
    profiles:
      - development

  debian-13.1:
    build: 
      context: ./
      dockerfile: ./debian-13.1/Dockerfile
    image: marcosbento/lumen:debian-13.1
    profiles:
      - development

  fedora-37:
    build: 
      context: ./
      dockerfile: ./fedora-37/Dockerfile
    image: marcosbento/lumen:fedora-37
    profiles:
      - development

  fedora-42:
    build: 
      context: ./
      dockerfile: ./fedora-42/Dockerfile
    image: marcosbento/lumen:fedora-42
    profiles:
      - development

  rocky-8.6:
    build: 
      context: ./
      dockerfile: ./rocky-8.6/Dockerfile
    image: marcosbento/lumen:rocky-8.6
    profiles:
      - development
  
  rocky-9.3:
    build: 
      context: ./
      dockerfile: ./rocky-9.3/Dockerfile
    image: marcosbento/lumen:rocky-9.3
    profiles:
      - development

  ubuntu-22.04:
    build: 
      context: ./
      dockerfile: ./ubuntu-22.04/Dockerfile
    image: marcosbento/lumen:ubuntu-22.04
    profiles:
      - development

  ubuntu-24.04:
    build: 
      context: ./
      dockerfile: ./ubuntu-24.04/Dockerfile
    image: marcosbento/lumen:ubuntu-24.04
    profiles:
      - development
      
