
name: dockerizing

on:
  schedule:
     - cron: "0 0 * * SAT"  # Run weekly on Saturdays at midnight UTC

  # Trigger the workflow on push to the stable branch
  push:
    branches:
      - stable

  # Trigger the workflow manually
  workflow_dispatch: ~

jobs:
  bootstrap:
    runs-on: ubuntu-latest

    outputs:
      timestamp: ${{ steps.timestamp.outputs.timestamp }}

    steps:
      - name: Collect timestamp
        id: timestamp
        run: echo "timestamp=$(date +'%Y%m%dT%H%M%S')" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest

    needs: bootstrap

    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        image:
          - 0dev
          - almalinux-8.10
          - almalinux-9.7
          - almalinux-10.1
          - alpine-3.23
          - arch-20260510
          - debian-11.11
          - debian-12.13
          - debian-13.5
          - fedora-44
          - opensuse-tumbleweed
          - ubuntu-22.04
          - ubuntu-24.04
          - ubuntu-26.04

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Print matrix parameters
        run: |
          echo "Image: ${{ matrix.image }}"
          echo "Timestamp: ${{ needs.bootstrap.outputs.timestamp }}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          file: ./${{ matrix.image }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/lumen:${{ matrix.image }}_${{ needs.bootstrap.outputs.timestamp }}
            ${{ vars.DOCKERHUB_USERNAME }}/lumen:${{ matrix.image }}
          labels: |
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ needs.bootstrap.outputs.timestamp }}
